"""
Auto-documentation generator for the SC2 Bot project.
Parses all Python files using the AST module, extracts docstrings,
and generates Markdown documentation including an API reference,
architecture overview, and module dependency graph.

Usage:
    python docs_gen/generate_docs.py [--root .] [--output docs/]
"""

from __future__ import annotations

import argparse
import ast
import sys
from collections import defaultdict
from pathlib import Path
from typing import NamedTuple

# ── Data structures ───────────────────────────────────────────────────────────


class FunctionDoc(NamedTuple):
    name: str
    docstring: str
    args: list[str]
    returns: str
    lineno: int


class ClassDoc(NamedTuple):
    name: str
    docstring: str
    bases: list[str]
    methods: list[FunctionDoc]
    lineno: int


class ModuleDoc(NamedTuple):
    path: str
    module_name: str
    docstring: str
    classes: list[ClassDoc]
    functions: list[FunctionDoc]
    imports: list[str]


# ── AST parsers ───────────────────────────────────────────────────────────────


def _get_docstring(node: ast.AST) -> str:
    """Extract docstring from a function, class, or module node."""
    if not (
        isinstance(
            node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Module)
        )
    ):
        return ""
    if (
        node.body
        and isinstance(node.body[0], ast.Expr)
        and isinstance(node.body[0].value, ast.Constant)
        and isinstance(node.body[0].value.value, str)
    ):
        return node.body[0].value.value.strip()
    return ""


def _parse_args(func: ast.FunctionDef | ast.AsyncFunctionDef) -> list[str]:
    args = [a.arg for a in func.args.args]
    if func.args.vararg:
        args.append(f"*{func.args.vararg.arg}")
    if func.args.kwarg:
        args.append(f"**{func.args.kwarg.arg}")
    return args


def _parse_returns(func: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    if func.returns is None:
        return ""
    return ast.unparse(func.returns)


def parse_function(node: ast.FunctionDef | ast.AsyncFunctionDef) -> FunctionDoc:
    return FunctionDoc(
        name=node.name,
        docstring=_get_docstring(node),
        args=_parse_args(node),
        returns=_parse_returns(node),
        lineno=node.lineno,
    )


def parse_class(node: ast.ClassDef) -> ClassDoc:
    bases = [ast.unparse(b) for b in node.bases]
    methods = [
        parse_function(n)
        for n in ast.walk(node)
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n is not node
    ]
    return ClassDoc(
        name=node.name,
        docstring=_get_docstring(node),
        bases=bases,
        methods=methods,
        lineno=node.lineno,
    )


def parse_module(path: Path, root: Path) -> ModuleDoc | None:
    try:
        source = path.read_text(encoding="utf-8", errors="ignore")
        tree = ast.parse(source, filename=str(path))
    except SyntaxError:
        return None

    module_name = ".".join(path.relative_to(root).with_suffix("").parts)
    imports: list[str] = []
    classes: list[ClassDoc] = []
    functions: list[FunctionDoc] = []

    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            imports.append(ast.unparse(node))
        elif isinstance(node, ast.ClassDef):
            classes.append(parse_class(node))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            # Top-level only
            if any(
                isinstance(p, ast.ClassDef)
                for p in ast.walk(tree)
                if node in ast.walk(p) and p is not tree
            ):
                continue
            functions.append(parse_function(node))

    return ModuleDoc(
        path=str(path.relative_to(root)),
        module_name=module_name,
        docstring=_get_docstring(tree),
        classes=classes,
        functions=functions,
        imports=imports,
    )


# ── Markdown generators ───────────────────────────────────────────────────────


def render_api_reference(modules: list[ModuleDoc]) -> str:
    lines = ["# API Reference\n", "_Auto-generated by docs_gen/generate_docs.py_\n"]
    for mod in sorted(modules, key=lambda m: m.module_name):
        lines.append(f"\n## `{mod.module_name}`\n")
        lines.append(f"**File**: `{mod.path}`\n")
        if mod.docstring:
            lines.append(f"\n{mod.docstring}\n")
        for cls in mod.classes:
            lines.append(f"\n### class `{cls.name}`")
            if cls.bases:
                lines.append(f" ({', '.join(cls.bases)})")
            lines.append("\n")
            if cls.docstring:
                lines.append(f"\n{cls.docstring}\n")
            for meth in cls.methods:
                sig = f"{meth.name}({', '.join(meth.args)})"
                if meth.returns:
                    sig += f" -> {meth.returns}"
                lines.append(f"\n- `{sig}`")
                if meth.docstring:
                    lines.append(f": {meth.docstring.split(chr(10))[0]}")
        for fn in mod.functions:
            sig = f"{fn.name}({', '.join(fn.args)})"
            if fn.returns:
                sig += f" -> {fn.returns}"
            lines.append(f"\n### `{sig}`\n")
            if fn.docstring:
                lines.append(f"\n{fn.docstring}\n")
    return "\n".join(lines)


def render_dependency_graph(modules: list[ModuleDoc]) -> str:
    lines = ["# Module Dependency Graph\n", "```\n"]
    for mod in modules:
        local_imports = [
            imp for imp in mod.imports if any(m.module_name in imp for m in modules)
        ]
        if local_imports:
            lines.append(f"{mod.module_name}")
            for imp in local_imports[:5]:
                lines.append(f"  -> {imp}")
    lines.append("```\n")
    return "\n".join(lines)


# ── Main ──────────────────────────────────────────────────────────────────────


def main(root: str = ".", output: str = "docs") -> None:
    root_path = Path(root).resolve()
    output_path = Path(output)
    output_path.mkdir(parents=True, exist_ok=True)

    py_files = [
        p
        for p in root_path.rglob("*.py")
        if ".git" not in p.parts
        and "venv" not in p.parts
        and "__pycache__" not in p.parts
    ]
    print(f"Parsing {len(py_files)} Python files...")

    modules = [m for p in py_files if (m := parse_module(p, root_path)) is not None]
    print(f"Successfully parsed {len(modules)} modules.")

    api_md = render_api_reference(modules)
    (output_path / "api_reference.md").write_text(api_md, encoding="utf-8")

    dep_md = render_dependency_graph(modules)
    (output_path / "dependency_graph.md").write_text(dep_md, encoding="utf-8")

    print(f"Documentation written to {output_path}/")
    print(f"  api_reference.md  ({len(api_md)} chars)")
    print(f"  dependency_graph.md ({len(dep_md)} chars)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="SC2 Bot Documentation Generator")
    parser.add_argument("--root", default=".", help="Project root directory")
    parser.add_argument("--output", default="docs", help="Output directory")
    args = parser.parse_args()
    main(args.root, args.output)
